language: php

php:
 - "7.4"
 - "8.0"
 - "8.1"

before_script:
 - composer self-update
 - composer --version
 - composer install -n --dev --prefer-source

script: composer run lint:check && composer run test
