language: php

php:
 - "5.3"
 - "5.4"
 - "5.5"

before_script:
 - composer self-update
 - composer --version
 - composer install -n --dev --prefer-source

script: vendor/bin/phpcs --standard=PSR2 src && vendor/bin/phpunit --coverage-text
